#! /usr/bin/env python

import sys
import numpy
from optparse import OptionParser
import matplotlib.pyplot as plt
import IPython

def get_summary(a):
    d = {
        'mean'   : numpy.mean(a),
        'median' : numpy.median(a),
        'std'    : numpy.std(a),
        '1p'     : numpy.percentile(a, 1),
        '1q'     : numpy.percentile(a, 25),
        '3q'     : numpy.percentile(a, 75),
        '99p'    : numpy.percentile(a, 99),
    }

    return d
        
def main():
    op = OptionParser()
    op.add_option("-H", "--histogram", dest="histogram",
                  action="store_true", default=False,
                  help="Show a histogram via matplotlib")
    op.add_option("-I", "--ipython", dest="ipython",
                  action="store_true", default=False,
                  help="Drop into an ipython shell")

    opts, args = op.parse_args()

    numbers = []
    if not args:
        fin = sys.stdin
    else:
        fin = open(args[0], 'rU')
    line = fin.readline()
    while line:
        numbers.append(float(line.strip()))
        try:
            line = fin.readline()
        except EOFError:
            line = None

    num_array = numpy.array(numbers)
    num_summary = get_summary(num_array)
    out = [ "%s: %f" % (k,num_summary[k]) for k in num_summary]
    out.sort()
    print('\n'.join(out))
    if opts.histogram:
        n, bins, patches = plt.hist(num_array, 100)
        plt.show()
    if opts.ipython:
        IPython.embed()

main()
        
